project_name: arangoctl

builds:
  -
    main: cmd/arangoctl/main.go
    binary: arangoctl
    ldflags:
      - -s -w
      - "-extldflags '-static'"
      - -X main.version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    goarm:
      - 7
    flags:
      - -trimpath

dockers:
- image_templates:
    - "ghcr.io/galaxyse/arangoctl:{{ .Version }}-amd64"
  use: buildx
  dockerfile: Dockerfile
  build_flag_templates:
    - "--platform=linux/amd64"
- image_templates:
    - "ghcr.io/galaxyse/arangoctl:{{ .Version }}-arm64"
  use: buildx
  goarch: arm64
  dockerfile: Dockerfile
  build_flag_templates:
    - "--platform=linux/arm64"

docker_manifests:
- name_template: ghcr.io/galaxyse/arangoctl:{{ .Version }}
  image_templates:
  - ghcr.io/galaxyse/arangoctl:{{ .Version }}-amd64
  - ghcr.io/galaxyse/arangoctl:{{ .Version }}-arm64
